CREATE DATABASE hotel;

CREATE USER hotel_user WITH PASSWORD 'R7hB2fK9sL6e';

ALTER DATABASE hotel OWNER TO hotel_user;

CREATE SCHEMA hotel;

ALTER SCHEMA hotel OWNER TO hotel_user;

CREATE TABLE hotel.client (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fio VARCHAR(256) NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    check_in_time TIMESTAMP,
    check_out_time TIMESTAMP
);

CREATE TABLE hotel.room (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number INT NOT NULL,
    capacity INT NOT NULL,
    price INT NOT NULL,
    status VARCHAR(16) NOT NULL,
    stars INT NOT NULL,
    check_in_time TIMESTAMP,
    check_out_time TIMESTAMP
);

CREATE TABLE hotel.service (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(16) NOT NULL,
    price INT NOT NULL,
    status VARCHAR(16) NOT NULL,
    service_time TIMESTAMP
);

CREATE TABLE hotel.room_reservation (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_id INT NOT NULL,
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP NOT NULL,
    FOREIGN KEY (room_id) REFERENCES hotel.room(id)
);

CREATE TABLE hotel.reservation_client (
    reservation_id INT,
    client_id INT,
    PRIMARY KEY (reservation_id, client_id),
    FOREIGN KEY (reservation_id) REFERENCES hotel.room_reservation(id),
    FOREIGN KEY (client_id) REFERENCES hotel.client(id)
);

CREATE TABLE hotel.provided_service (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id INT NOT NULL,
    service_id INT NOT NULL,
    service_time TIMESTAMP NOT NULL,
    FOREIGN KEY (client_id) REFERENCES hotel.client(id),
    FOREIGN KEY (service_id) REFERENCES hotel.service(id)
);
